### ISSUE TITLE
Investigate deployment solutions

### ISSUE THREAD

**Issue by matedro** [Palmyra-Racing-Association/clubmanager-2.0#129]
# Description
Determine how the backend will be deployed to AWS, whether that be an automated process of some kind (Terraform + Ansible?) or a manual process.

# Acceptance Criteria
- [ ] A decision has been made
- [ ] Additional tickets have been created if necessary
- [ ] Unit tests are updated
- [ ] Unit tests pass

**Comment by adelimon** [comment]
This is completed - using CDK and Docker to do this.  See `devops/deploy` directory.
