### ISSUE TITLE
Track Status Card

### ISSUE THREAD

**Issue by cjs8487** [Palmyra-Racing-Association/clubmanager-2.0#84]
# Description
Create a dashboard card displaying the track status

# Acceptance Criteria
- [x] Track statuses are properly displayed
- [x] Admins have an edit button
- [x] Admins can toggle the status of the tracks after clicking the edit button
- [x] Unit tests are updated
- [x] Unit tests pass

**Comment by adelimon** [comment]
Complete, this is now editable on the dashboard.

![image](https://user-images.githubusercontent.com/8899219/185198871-1b932ad7-7468-4582-93ea-f50b6a003f68.png)
