### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by cjs8487** [Palmyra-Racing-Association/clubmanager-2.0#90]
# Description
Add a search bar to the calendar that filters the events in the calendar

# Acceptance Criteria
- [ ] Search bar exists
- [ ] Entering text into the search bar filters by event title
- [ ] Filter toggles for event types
- [ ] Unit tests are updated
- [ ] Unit tests pass

**Comment by adelimon** [comment]
Given the direction the calendar has taken I'm not sure this makes sense any more.  Closing it, might revisit with a different calendar view.
