### ISSUE TITLE
Unverified Toggle

### ISSUE THREAD

**Issue by cjs8487** [Palmyra-Racing-Association/clubmanager-2.0#95]
# Description
Add a toggle that filters out verified signups from the page

# Acceptance Criteria
- [ ] Toggle exists
- [ ] Toggle properly filters
- [ ] Unit tests are updated
- [ ] Unit tests pass

**Comment by adelimon** [comment]
Closing as I've taken verified/non verified out of the app to simplify summation of points totals.
